### ISSUE TITLE
BUG: Critical error when deleting the example workspace

### ISSUE THREAD

**Issue by romshark** [graph-guard/ggproxy-playground#8]
<img width="422" alt="Screenshot 2023-03-21 at 20 17 39" src="https://user-images.githubusercontent.com/9574743/226717542-e2f7ad6f-3090-4cd7-9510-c2b0bb0295c5.png">

![bug_4](https://user-images.githubusercontent.com/9574743/226717257-6b55121f-4149-4e61-a183-aa3f5c65b85a.gif)

**Comment by DanielSharkov** [comment]
fixed by de7ba5464c9a8a43cb6bca89b5be2bcd6308cd37
